- hosts: all
  become: yes  
  tasks:
  - name: Install packages
    ansible.builtin.apt:
      name: tree
      update_cache: yes 
    register: hello            # same as hello = sudo yum apt install 
  
  - name: Debug mode 
    debug:
      msg: "{{ hello }}"
    